delivery/app/accounts/urls.py
from django.conf.urls import url, include
from delivery.app.accounts import views

urlpatterns = [

    url(r'^perfil/$',  views.ShowProfile.as_view(),  name='user_profile'),
	url(r'^password/$', views.change_password, name='change_password'),
    
    url(r'^criar/$',  views.CreateUser.as_view(),  name='user_create'),
    url(r'^edit/(?P<pk>[0-9]+)/$',  views.UpdateUser.as_view(),  name='user_update'),
    url(r'^(?P<pk>[0-9]+)/$',  views.ShowUser.as_view(),  name='user_show'),
    url(r'^',  views.index,  name='users'),


]

delivery/app/clients/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from delivery.app.clients import views

urlpatterns = [
    url(r'^criar/$', views.CreateClient.as_view(), name='CreateClient'),
    url(r'^atualizar/(?P<pk>[0-9]+)/$', views.UpdateClient.as_view(), name='UpdateClient'),
    url(r'^(?P<pk>[0-9]+)/$', views.ShowClient.as_view(), name='ShowClient'),
    url(r'^', views.index, name='clients'),

]

delivery/app/core/urls.py
from django.conf.urls import url, include
from delivery.app.core import views

urlpatterns = [
    url(r'^usuarios/', include('delivery.app.accounts.urls', namespace='accounts')),
    url(r'^produtos/', include('delivery.app.products.urls', namespace='products')),
    url(r'^categorias/', include('delivery.app.categories.urls', namespace='categories')),
    url(r'^promocoes/', include('delivery.app.promotions.urls', namespace='promotions')),
    url(r'^clientes/', include('delivery.app.clients.urls', namespace='clients')),
    url(r'^pedidos/', include('delivery.app.requests.urls', namespace='requests')),

    url(r'^help/',  views.help, name='help'),
    url(r'^',  views.index, name='dashboard'),

]

delivery/app/products/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from delivery.app.products import views



urlpatterns = [
    url(r'^criar/$',  views.CreateProduct.as_view(),  name='CreateProduct'),
    url(r'^atualizar/(?P<pk>[0-9]+)/$',  views.UpdateProduct.as_view(),  name='UpdateProduct'),
    url(r'^(?P<pk>[0-9]+)/$',  views.ShowProduct.as_view(),  name='ShowProduct'),
    url(r'^',  views.index,  name='products'),
   

]

delivery/app/requests/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from delivery.app.requests import views

urlpatterns = [
    url(r'^criar/$', views.CreateRequest.as_view(), name='CreateRequest'),
    url(r'^atualizar/(?P<pk>[0-9]+)/$', views.UpdateRequest.as_view(), name='UpdateRequest'),
    url(r'^(?P<pk>[0-9]+)/$', views.ShowRequest.as_view(), name='ShowRequest'),
    url(r'^', views.index, name='requests'),

]

delivery/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.auth import views as auth_views
from delivery.mysite import views
from django.conf import settings
from django.conf.urls.static import static

#from django.contrib.auth.decorators import login_required

urlpatterns = [

    url(r'^login/$', auth_views.login, {'template_name': 'accounts/auth/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/login'}, name='logout'),
    
    #url(r'^painel/', login_required(include('delivery.app.core.urls'))),
    url(r'^painel/', include('delivery.app.core.urls')),

    url(r'^', include('delivery.mysite.urls')),
    url(r'^contact/', views.contact, name='contact'),

    url(r'^admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

delivery/app/core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
# Create your models here.

delivery/app/core/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms

from delivery.app.core.models import Address
from django.core.exceptions import ValidationError


class AddressForm(forms.ModelForm):

    #Address
    city = forms.CharField(widget=forms.TextInput(attrs={}),label = 'Cidade')
    state = forms.CharField(widget=forms.EmailInput(attrs={}), label = 'Estado')

    class Meta:
        model = Address
        fields = ['state', 'city']



    

delivery/app/core/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from delivery.app.clients.models import Clients
from delivery.app.products.models import Products

@login_required
def index(request):
    #return HttpResponse("Olá Core")
    template = loader.get_template('core/index.html')
    context = {
        'data': [],
        'clients': Clients.objects.count(),
        'products' : Products.objects.count(),
    }
    #return HttpResponse(Clients.objects.count())
    return HttpResponse(template.render(context, request))

def help(request):
    #return HttpResponse("Olá Core")
    template = loader.get_template('core/help.html')
    context = {
        'data': [],
    }
    return HttpResponse(template.render(context, request))

delivery/app/core/templates/layouts/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="Sistema Delivery" />
    <meta name="keywords" content="Pedidos, gerenciamento de pedidos delivery" />
    <meta name="author" content="ToDelivery" />
  
  <title>To Delivery</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
  <link rel="stylesheet" href="https://materializecss.com/css/ghpages-materialize.css"/>

  {% block after-styles-end %}
        
  {% endblock %}
</head>

<body class="brown lighten-5">

<div class="navbar-fixed">
  <nav role="navigation">
      <div class="nav-wrapper container">
      {% include "layouts/header.html" %}
      </div>
  </nav>
</div>
<div class="container">
    <div class="section">
        {% block content %}{% endblock %}
    </div>
</div>

<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <!-- Compiled and minified JavaScript -->
<script src="{% static 'materialize/js/materialize.min.js' %}"></script>
<script type="text/javascript">
 $(document).ready(function() {
  //$('select').prop('multiple','multiple'); 
  $('select').material_select();
    
  });
</script>
{% block after-scripts-end %}
        
{% endblock %}
   

</body>
</html>

delivery/app/core/templates/layouts/header.html
<a id="logo-container" href="{% url 'dashboard' %}" class="brand-logo">ToDelivery</a>
<ul class="right hide-on-med-and-down">

  {% if request.user.is_authenticated %}
    <ul id="dropdown-app" class="dropdown-content">
      <li><a href="#">Meus Pedidos</a></li> 

    </ul>

    <li><a href="{% url 'requests:requests' %}"><i class="material-icons left">local_dining</i>Pedidos</a></li>

    <ul id="dropdown-gerencia" class="dropdown-content">
      <li><a href="{% url 'clients:clients' %}">Clientes</a></li>
      <li><a href="{% url 'products:products' %}">Produtos</a></li>
      <li><a href="{% url 'promotions:promotions' %}">Promoções</a></li>
      <li><a href="{% url 'categories:categories' %}">Categorias</a></li>
    </ul>
    <li><a class="dropdown-button" data-activates="dropdown-gerencia"><i class="material-icons left">settings</i> Gerenciar<i class="material-icons right">arrow_drop_down</i></a></li>


    <ul id="dropdown1" class="dropdown-content">
      <li><a href="{% url 'dashboard' %}">Painel de Controle</a></li>
      <li><a href="{% url 'accounts:user_profile' %}">Definições de usuário</a></li>
      <li><a href="{% url 'accounts:users' %}">Gerenciar Usuários</a></li>
      <li><a href="{% url 'help' %}">Ajuda</a></li>

      <li class="divider"></li>
      <li><a href="{% url 'logout' %}"><i class="material-icons left">input</i>Sair</a></li>
    </ul>
    <li><a class="dropdown-button" data-activates="dropdown1"><i class="material-icons left">perm_identity</i>{{ request.user.name }}<i class="material-icons right">arrow_drop_down</i></a></li>

  {% else %}

  <li><a href="{% url 'login' %}">Login</a></li>
  <li><a href="{% url 'contact' %}">Contato</a></li>

  {% endif %}
</ul>