delivery/app/categories/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from delivery.app.categories import views



urlpatterns = [
    url(r'^criar/$',  views.CreateCategories.as_view(),  name='CreateCategories'),
    url(r'^atualizar/(?P<pk>[0-9]+)/$',  views.UpdateCategories.as_view(),  name='UpdateCategories'),
    url(r'^(?P<pk>[0-9]+)/$',  views.ShowCategories.as_view(),  name='ShowCategories'),
    url(r'^',  views.index,  name='categories'),
   

]

delivery/app/core/urls.py
from django.conf.urls import url, include
from delivery.app.core import views

urlpatterns = [
    url(r'^usuarios/', include('delivery.app.accounts.urls', namespace='accounts')),
    url(r'^produtos/', include('delivery.app.products.urls', namespace='products')),
    url(r'^categorias/', include('delivery.app.categories.urls', namespace='categories')),
    url(r'^promocoes/', include('delivery.app.promotions.urls', namespace='promotions')),
    url(r'^clientes/', include('delivery.app.clients.urls', namespace='clients')),
    url(r'^pedidos/', include('delivery.app.requests.urls', namespace='requests')),

    url(r'^help/',  views.help, name='help'),
    url(r'^',  views.index, name='dashboard'),

]

delivery/app/products/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from delivery.app.products import views



urlpatterns = [
    url(r'^criar/$',  views.CreateProduct.as_view(),  name='CreateProduct'),
    url(r'^atualizar/(?P<pk>[0-9]+)/$',  views.UpdateProduct.as_view(),  name='UpdateProduct'),
    url(r'^(?P<pk>[0-9]+)/$',  views.ShowProduct.as_view(),  name='ShowProduct'),
    url(r'^',  views.index,  name='products'),
   

]

delivery/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.auth import views as auth_views
from delivery.mysite import views
from django.conf import settings
from django.conf.urls.static import static

#from django.contrib.auth.decorators import login_required

urlpatterns = [

    url(r'^login/$', auth_views.login, {'template_name': 'accounts/auth/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/login'}, name='logout'),
    
    #url(r'^painel/', login_required(include('delivery.app.core.urls'))),
    url(r'^painel/', include('delivery.app.core.urls')),

    url(r'^', include('delivery.mysite.urls')),
    url(r'^contact/', views.contact, name='contact'),

    url(r'^admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

delivery/app/products/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from delivery.app.categories.models import Categories

class Products(models.Model):
    produto = models.CharField('Produto',max_length=100)
    descricao_produto = models.CharField('Descrição do Produto',max_length=500)
    quantidade_estoque = models.IntegerField('Quantidade em Estoque')
    preco = models.DecimalField('Preço',max_digits=5,decimal_places=2)
    imagem = models.ImageField("Imagem", upload_to='images/products')
    
    categoria = models.ForeignKey(Categories, default="", on_delete=models.CASCADE)

    def __str__(self):
        return self.descricao_produto

delivery/app/products/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms
from models import Products
#from django.contrib.auth.forms import ProductsCreationForm

#from django.core.exceptions import ValidationError ../categories/{% url 'categories:IndexCategories' %}


class ProductsForm(forms.ModelForm):
    '''
    produto = forms.CharField(widget=forms.TextInput(attrs={}),label = 'Nome do produto')
    descricao_produto = forms.CharField(widget=forms.TextInput(attrs={}), label = 'Descrição do Produto')
    quantidade_estoque = forms.CharField( widget=forms.IntegerField(),label='Quantidade em Estoque')
    preco = forms.CharField(widget=forms.DecimalField(), label='Preço')
    imagem = forms.CharField(widget=forms.TextInput(attrs={}),label = 'Imagem do Produto')
    '''
    class Meta:
        model = Products
        fields = ['produto', 'descricao_produto', 'preco', 'quantidade_estoque', 'imagem', 'categoria']

'''
class ProductsEditForm(forms.ModelForm):
    produto = forms.CharField(widget=forms.TextInput(attrs={}), label='Nome do produto')
    descricao_produto = forms.CharField(widget=forms.CharField(attrs={}), label='Descrição do Produto')
    quantidade_estoque = forms.CharField(widget=forms.IntegerField, label='Quantidade em Estoque')
    preco = forms.DecimalField(widget=forms.DecimalField, label='Preço')
    imagem = forms.CharField(widget=forms.TextInput(attrs={}), label='Imagem do Produto')

    class Meta:
        model = Products
        fields = ['produto', 'descricao_produto', 'preco', 'quantidade_estoque', 'imagem']
'''

class ProductsShowForm(forms.ModelForm):

    produto = forms.CharField(widget=forms.TextInput(attrs={}), label='Nome do produto',disabled=True)
    descricao_produto = forms.CharField(widget=forms.TextInput(attrs={}), label='Descrição do produto',disabled=True)
    quantidade_estoque = forms.CharField(disabled=True)
    preco = forms.CharField(disabled=True)

    class Meta:
        model = Products
        fields = ['produto', 'descricao_produto', 'preco', 'quantidade_estoque', 'imagem', 'categoria']

delivery/app/products/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect

from django.core.urlresolvers import reverse, reverse_lazy

from django.views.generic.edit import CreateView, UpdateView, DeleteView

from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader

from models import Products
from delivery.app.products.forms import ProductsForm, ProductsShowForm

from django.contrib import messages


#from django.contrib.auth.forms import UserCreationForm


def index(request):
    template = loader.get_template('products/index.html')
    products = Products.objects.all()
    context = {
        'data': [],
        'products': products,
    }
    return HttpResponse(template.render(context, request))
'''
def product_create(request):
    template = loader.get_template('products/prod_create.html')
    context = {
        'data': [],
    }

    return HttpResponse(template.render(context, request))
'''

class CreateProduct(CreateView):
    model = Products
    template_name = 'products/form.html'
    form_class = ProductsForm
    success_url = reverse_lazy('products:products')
    '''
    def get(self, request, *args, **kwargs):
        self.object = None
        form = self.form_class
        return self.render_to_response(
            self.get_context_data(
                form=form
            )
        )

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.form_class(self.request.POST)

        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):

        self.object = form.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form):
        return self.render_to_response(
            self.get_context_data(
                form=form
            )
        )

    def get_success_url(self):
        return reverse_lazy('accounts:products')
    '''

class UpdateProduct(UpdateView):
    model = Products
    template_name = 'products/form.html'
    form_class = ProductsForm
    success_url = reverse_lazy('products:products')

'''
    def get(self, request, *args, **kwargs):
        self.object = None
        form = self.form_class
        address_form = self.second_form_class

        return self.render_to_response(
            self.get_context_data(
                form=form,
                address_form=address_form
            )
        )

    def get_context_data(self, **kwargs):
        self.object = self.get_object()
        context = super(UpdateUser, self).get_context_data(**kwargs)
        context['address_form'] = self.second_form_class(instance=self.object.address)
        context['form'] = self.form_class(instance=self.object)

        return context

    def post(self, request, *args, **kwargs):

        self.object = self.get_object()

        address_form = self.second_form_class(self.request.POST, instance=self.object.address)
        form = self.form_class(self.request.POST, instance=self.object)

        if form.is_valid():
            print('Valido')
            return self.form_valid(form, address_form)
        else:
            print('inValido')
            return self.form_invalid(form, address_form)

    def form_valid(self, form, address_form):
        form.save()
        address_form.save()

        messages.success(self.request, 'Usuario atualizado com sucesso.')
        return HttpResponseRedirect(reverse('accounts:users'))

    def form_invalid(self, form, address_form):
        return self.render_to_response(
            self.get_context_data(
                form=form,
                address_form=address_form
            )
        )
    '''

class ShowProduct(UpdateView):
    model = Products
    template_name = 'products/form.html'
    form_class = ProductsShowForm
    success_url = reverse_lazy('products:products')

    '''
    def get(self, request, *args, **kwargs):
        self.object = None
        form = self.form_class
        address_form = self.second_form_class

        return self.render_to_response(
            self.get_context_data(
                form=form,
                address_form=address_form
            )
        )

    def get_context_data(self, **kwargs):
        self.object = self.get_object()
        context = super(ShowUser, self).get_context_data(**kwargs)
        context['address_form'] = self.second_form_class(instance=self.object.address)
        context['form'] = self.form_class(instance=self.object)

        return context

    '''

'''
def list_products(request):
	products = Products.objects.all()
	return render(request,'products.html',{'products': products})
'''

delivery/app/products/templates/products/form.html
{% extends 'layouts/base.html' %}


{% block content %}
<div class="col s12">

	{% if request.resolver_match.url_name == 'ShowProduct' %}

	<h4>Ver Produto</h4>

	{% elif request.resolver_match.url_name == 'CreateProduct' %}

	<h4>Cadastrar Produto</h4>

	{% elif request.resolver_match.url_name == 'UpdateProduct' %}

	<h4>Atualizar Produto</h4>

	{% endif %}
	<div class="card">
		<div class="card-content">
			<form action="#" method="POST" enctype="multipart/form-data">
				{% csrf_token %}

				<div class="row">
					<div class="input-field col s3">
						<label for="#{{ form.produto.id_for_label }}">{{ form.produto.label }}</label>
						{{ form.produto }}
					</div>
					<div class="input-field col s5">
						<label for="#{{ form.descricao_produto.id_for_label }}">{{ form.descricao_produto.label }}</label>
						{{ form.descricao_produto }}

					</div>
					<div class="input-field col s4">
						<label for="#{{ form.categoria.id_for_label }}"></label>
						{{ form.categoria }}
					</div>
					<div class="input-field col s2">
						<label for="#{{ form.preco.id_for_label }}">{{ form.preco.label }}</label>
						{{ form.preco }}
					</div>
					<div class="input-field col s3">
						<label for="#{{ form.quantidade_estoque.id_for_label }}">{{ form.quantidade_estoque.label }}</label>
						{{ form.quantidade_estoque }}
					</div>
					<div class="input-field col s7">
						<label for="#{{ form.imagem.id_for_label }}"></label>
						{{ form.imagem }}
					</div>
<!--
					<div class="input-field col s2">
						<label for="#{{ address_form.state.id_for_label }}">{{ address_form.state.label }}</label>
						{{ address_form.state }}
					</div>
					<div class="input-field col s3">
						<label for="#{{ address_form.city.id_for_label }}">{{ address_form.city.label }}</label>
						{{ address_form.city }}
					</div>
					<div class="input-field col s3">
						<label for="#{{ address_form.city.id_for_label }}">{{ address_form.zip_code.label }}</label>
						{{ address_form.zip_code }}
					</div>

					<div class="input-field col s4">	
						<label for="#{{ address_form.street.id_for_label }}">{{ address_form.street.label }}</label>
						{{ address_form.street }}
					</div>

					<div class="input-field col s4">	
						<label for="#{{ address_form.neighborhood.id_for_label }}">{{ address_form.neighborhood.label }}</label>
						{{ address_form.neighborhood }}
					</div>
					<div class="input-field col s8">	
						<label for="#{{ address_form.neighborhood.id_for_label }}">{{ address_form.complement.label }}</label>
						{{ address_form.complement }}
					</div>


					<div class="input-field col s5">
						<label for="#{{ form.password1.id_for_label }}">{{ form.password1.label }}</label>
						{{ form.password1 }}
					</div>
					<div class="input-field col s5">
						<label for="#{{ form.password2.id_for_label }}">{{ form.password2.label }}</label>
						{{ form.password2 }}
						{{ form.password2.errors }}
					</div>
					<div class="input-field col s2" style="margin-top: 30px">

						<p>
							<label>
								{{ form.is_active }}
								<span>{{ form.is_active.label }}</span>
							</label>
						</p>
					</div>
				</div>
!-->

				{% if request.resolver_match.url_name == 'ShowProduct' %}

				<div class="col s12 right-align">
					 <a href="{% url 'products:UpdateProduct' object.id %}"class="btn btn-primary">
						<i class="fa fa-btn fa-sign-in"></i> Editar
					</a>
					<button type="submit" class="btn btn-primary">
						<i class="fa fa-btn fa-sign-in"></i> Voltar
					</button>
				</div>

				{% elif request.resolver_match.url_name == 'CreateProduct' %}

				<div class="col s12 right-align">
					<button type="submit" class="btn btn-primary">
						<i class="fa fa-btn fa-sign-in"></i> Cadastrar
					</button>
				</div>

				{% elif request.resolver_match.url_name == 'UpdateProduct' %}

				<div class="col s12 right-align">
					<button type="submit" class="btn btn-primary">
						<i class="fa fa-btn fa-sign-in"></i> Atualizar
					</button>
				</div>

				{% endif %}


			</form>
		</div>
	</div>
</div>
{% endblock %}

delivery/app/products/templates/products/index.html
{% extends 'layouts/base.html' %}

{% load staticfiles %}

{% block content %}

<div class="col s12 m12">
  <div class="card">
    <div class="card-content">

      <table>
        <thead>
          <tr>
            <th>Imagem</th>
            <th>Produto</th>
            <th>Descrição do Produto</th>
            <th>Categoria</th>
            <th>Quantidade</th>
            <th>Preço</th>
            <th> </th>
            <th class="center-align">Ação</th>
          </tr>
        </thead>

        <tbody>
          {% if products %}
          
          {% for product in products %}
          <tr>
            <td><img width="60%" class="responsive-img" src="/media/{{ product.imagem }}"></td>
            <td>{{ product.produto }}</td>
            <td>{{ product.descricao_produto }}</td>
            <td>{{ product.categoria }}</td>
            <td>{{ product.quantidade_estoque }}</td>
            <td>{{ product.preco }}</td>
            <!--td>
               <div style="font-size:.8em">
                 
               </div>
            </td!-->

            <td></td>
            <td width="140" class="center-align">
            	
                <a href="{% url 'products:ShowProduct' product.id %}">
                    <i class="small material-icons tooltipped" data-position="left" data-delay="50" data-tooltip="Mostrar" style="margin-right: 10px; color: green">visibility</i>
              	</a>
                  <a href="{% url 'products:UpdateProduct' product.id %}">
                      <i class="small material-icons tooltipped" data-position="right" data-delay="50" data-tooltip="Editar" style="margin-right: 10px">edit</i>
                  </a>
            </td>
          </tr>
          {% endfor %}
          {% else %}
 			    <tr>
                <td class="center-align" colspan="6"><br>Lista de produtos vazia!</td>
            </tr>
    	  {% endif %} 
           
        </tbody>
      </table>

    </div>
  </div>
</div>  

<div class="fixed-action-btn">
	<a href="{% url 'products:CreateProduct' %}" class="btn-floating btn-large">
		<i class="material-icons tooltipped" data-position="left" data-delay="50" data-tooltip="Cadastrar Produto">add</i>
	</a>
  	<ul>
		<li><a href="{% url 'categories:categories' %} " class="btn-floating green"><i class="material-icons tooltipped" data-position="left" data-delay="50" data-tooltip="Gerenciar Categorias">note</i></a></li>
	</ul>
</div>
{% endblock %}